version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    restart: always
    env_file: ../.env
    user: ${PUID}:${DOKER_GID}
    ports:
      - 3000:3000
    volumes:
      - ${SERVICE_DATA}/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations
