version: "3"

services:
  koillection:
    image: koillection/koillection
    container_name: koillection
    restart: unless-stopped
    ports:
      - 9280:80
    depends_on:
      - db
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - APP_DEBUG=0
      - APP_ENV=prod
      # - APP_SECRET=
      - HTTPS_ENABLED=0
      - UPLOAD_MAX_FILESIZE=20M
      - PHP_MEMORY_LIMIT=512M
      - PHP_TZ=${TZ}
      - CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
      - JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem
      - JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem
      # - DB_DRIVER=pdo_pgsql
      # - DB_PORT=5432
      - DB_DRIVER=pdo_mysql
      - DB_PORT=3306
      - DB_HOST=db
      - DB_VERSION=16
      - DB_NAME=koillection
      - DB_USER=koillection
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${SERVICE_DATA}/koillection/conf:/conf
      - ${SERVICE_DATA}/koillection/uploads:/uploads
    labels:
      - homepage.group=Files
      - homepage.name=Koillection
      - homepage.icon=koillection.png
      - homepage.href=http://${INTERNAL_ADDR}:9280/
      - homepage.description=Collections manager
  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - MYSQL_DATABASE=koillection
      - MYSQL_USER=koillection
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ${SERVICE_DATA}/koillection/mysql:/var/lib/mysql

  #   image: postgres:16
  #   container_name: db
  #   restart: unless-stopped
  #   environment:
  #       - POSTGRES_DB=koillection
  #       - POSTGRES_USER=koillection
  #       - POSTGRES_PASSWORD=${DB_PASSWORD}
  #   volumes:
  #       - ${SERVICE_DATA}/koillection/postgresql:/var/lib/postgresql/data"
