version: "3.7"

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
      # - TRANSMISSION_WEB_HOME= #optional
      # - USER= #optional
      # - PASS= #optional
      # - WHITELIST= #optional
      # - PEERPORT= #optional
      # - HOST_WHITELIST= #optional
    volumes:
      - ${SERVICE_DATA}/transmission/config:/config
      - ${SHARED_DATA}/downloads:/downloads
      - ${SHARED_DATA}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - homepage.group=Download
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://${INTERNAL_ADDR}:9091/
      - homepage.description=Torrent client
      - homepage.widget.type=transmission
      - homepage.widget.url=http://${INTERNAL_ADDR}:9091/
