version: "3.7"

services:
  calibre_web:
    image: linuxserver/calibre-web
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ${SERVICE_DATADIR}/calibre/config:/config # Where calibre-web stores the internal database and config.
      - ${DATADIR}/shared/books:/books # Where your calibre database is located
    ports:
      - 8083:8083
    labels:
      - homepage.group=Media
      - homepage.name=Calibre-Web
      - homepage.icon=calibre-web.png
      - homepage.href=http://${INTERNAL_ADDR}:8083/
      - homepage.description=Ebook server

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
    ports:
      - 13378:80
    volumes:
      - ${SERVICE_DATADIR}/audiobookshelf/metadata:/metadata
      - ${SERVICE_DATADIR}/audiobookshelf/config:/config
      - ${DATADIR}/shared/audiobooks:/audiobooks
    labels:
      - homepage.group=Media
      - homepage.name=AudioBookShelf
      - homepage.icon=audiobookshelf.png
      - homepage.href=http://${INTERNAL_ADDR}:13378/
      - homepage.description=Audiobook server
      - homepage.widget.type=audiobookshelf
      - homepage.widget.url=http://${INTERNAL_ADDR}:13378/
      - homepage.widget.key=${AUDIOBOOKSHELF_API_KEY}

  lazylibrarian:
    image: linuxserver/lazylibrarian:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - DOCKER_MODS=linuxserver/mods:universal-calibre|linuxserver/mods:lazylibrarian-ffmpeg
    volumes:
      - ${SERVICE_DATADIR}/lazylibrarian/config:/config
      - ${DATADIR}/shared/books:/books
      - ${DATADIR}/shared/downloads:/downloads
      - ${DATADIR}/shared/audiobooks:/audiobooks
      - ${DATADIR}/shared/magazines:/magazines
      - ${DATADIR}/shared/comics:/comics
    ports:
      - 5299:5299
    labels:
      - homepage.group=Media
      - homepage.name=LazyLibrarian
      - homepage.icon=lazylibrarian.png
      - homepage.href=http://${INTERNAL_ADDR}:5299/
      - homepage.description=Ebook releases manager
