version: "3.7"

services:
  filebrowser:
    image: hurlenko/filebrowser
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - FB_BASEURL=/filebrowser
    ports:
      - 9180:8080
    volumes:
      - ${SHARED_DATA}/downloads:/downloads
      - ${SERVICE_DATA}/filebroser/config:/config
    labels:
      - homepage.group=Files
      - homepage.name=filebrowser
      - homepage.icon=filebrowser.png
      - homepage.href=http://${INTERNAL_ADDR}:9180/
      - homepage.description=File server
      - homepage.widget.type=filebrowser
      - homepage.widget.url=http://${INTERNAL_ADDR}:9180/
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - ${SERVICE_DATA}/transmission/config:/config
      - ${SHARED_DATA}/downloads:/downloads
      - ${SHARED_DATA}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    labels:
      - homepage.group=Files
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://${INTERNAL_ADDR}:9091/
      - homepage.description=Torrent client
      - homepage.widget.type=transmission
      - homepage.widget.url=http://${INTERNAL_ADDR}:9091/
