services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.8.0
    restart: unless-stopped
    ports:
      - 9925:9000
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ${SERVICE_DATADIR}/mealie/data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://${INTERNAL_ADDR}
    labels:
      - homepage.group=Tools
      - homepage.name=Mealie
      - homepage.icon=mealie.png
      - homepage.href=http://${INTERNAL_ADDR}:9925/
      - homepage.description=Recipe manager
