version: "2"

services:
  homeassistant:
    image: linuxserver/homeassistant
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
    volumes:
      - ${SERVICE_DATA}/homeassistant/config:/config # Contains all relevant configuration files.
    ports:
      - 8123:8123
    labels:
      - homepage.group=Smart Home
      - homepage.name=HomeAssistant
      - homepage.icon=home-assistant.png
      - homepage.href=http://${INTERNAL_ADDR}:8123/
      - homepage.description=Smart home automation manager
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883/tcp"
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
    volumes:
      - ${SERVICE_DATA}/mosquitto:/mosquitto
