version: "2"

services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    # command: --admin-password ${PORTAINER_ADMIN_PW}
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICE_DATA}/portainer/data:/data
    labels:
      - homepage.group=System
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=http://${INTERNAL_ADDR}:9000/
      - homepage.description=Containers manager
  reset_password:
    image: portainer/helper-reset-password
    volumes:
      - ${SERVICE_DATA}/portainer/data:/data
    profiles: ["dev"]
