networks:
  internal_network:
    external: true

services:
  portainer:
    image: portainer/portainer-ce
    restart: always
    env_file: ../.env
    # command: --admin-password ${PORTAINER_ADMIN_PW}
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${SERVICE_DATA}/portainer/data:/data
    labels:
      - homepage.group=System
      - homepage.name=Portainer
      - homepage.icon=portainer.png
      - homepage.href=http://portainer.server.home
      - homepage.description=Containers manager
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.server.home`)
      - traefik.http.routers.portainer.entrypoints=web
      - traefik.http.services.portainer.loadbalancer.server.port=9000
    networks:
      internal_network:
  reset_password:
    image: portainer/helper-reset-password
    volumes:
      - ${SERVICE_DATA}/portainer/data:/data
    env_file: ../.env
    profiles: [ "dev" ]
