version: "2"

services:
  heimdall:
    image: linuxserver/heimdall
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
    volumes:
      - ${SERVICE_DATA}/heimdall:/config
    ports:
      - 9080:80
      - 9443:443
    env_file: ../.env
