services:
  miniserve:
    image: docker.io/svenstaro/miniserve
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - MINISERVE_MKDIR_ENABLED=true
      - MINISERVE_SHOW_WGET_FOOTER=true
      - MINISERVE_DIRS_FIRST=true
      - MINISERVE_README=true
      - MINISERVE_ENABLE_TAR=true
      - MINISERVE_ENABLE_TAR_GZ=true
    ports:
      - ${MINISERVE_PORT:-9480}:8080
    volumes:
      - ${SHARED_DATA}/downloads:/data/downloads
      - ${SERVICE_DATA}/miniserve/config:/config
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=miniserve
      - homepage.icon=files.png
      - homepage.href=http://${INTERNAL_ADDR}:${MINISERVE_PORT:-9480}/
      - homepage.description=File server
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`miniserve.home.server`)
      - traefik.http.routers.whoami.entrypoints=web
    command: /data --upload-files
  filebrowser:
    image: hurlenko/filebrowser
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - FB_BASEURL=/filebrowser
    ports:
      - ${FILEBROWSER_PORT:-9180}:8080
    volumes:
      - ${SHARED_DATA}/downloads:/data/downloads
      - ${SERVICE_DATA}/filebroser/config:/config
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=filebrowser
      - homepage.icon=filebrowser.png
      - homepage.href=http://${INTERNAL_ADDR}:${FILEBROWSER_PORT:-9180}/
      - homepage.description=File server
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - ${SERVICE_DATA}/transmission/config:/config
      - ${SHARED_DATA}/downloads:/downloads
      - ${SHARED_DATA}/watch:/watch
    ports:
      - ${TRANSMISSION_UI_PORT:-9091}:9091
      - 51413:51413
      - 51413:51413/udp
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://${INTERNAL_ADDR}:${TRANSMISSION_UI_PORT:-9091}/
      - homepage.description=Torrent client
networks: {}
