networks:
  internal_network:
    external: true

services:
  miniserve:
    image: docker.io/svenstaro/miniserve
    restart: always
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - MINISERVE_MKDIR_ENABLED=true
      - MINISERVE_SHOW_WGET_FOOTER=true
      - MINISERVE_DIRS_FIRST=true
      - MINISERVE_README=true
      - MINISERVE_ENABLE_TAR=true
      - MINISERVE_ENABLE_TAR_GZ=true
    volumes:
      - ${SHARED_DATA}/downloads:/data/downloads
      - ${SERVICE_DATA}/miniserve/config:/config
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=miniserve
      - homepage.icon=files.png
      - homepage.href=http://miniserve.server.home/
      - homepage.description=File server
      - traefik.enable=true
      - traefik.http.routers.miniserve.rule=Host(`miniserve.server.home`)
      - traefik.http.routers.miniserve.entrypoints=web
      - traefik.http.services.miniserve.loadbalancer.server.port=8080
    command: /data --upload-files
    networks:
      internal_network:
  filebrowser:
    image: hurlenko/filebrowser
    restart: always
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - FB_BASEURL=/filebrowser
    volumes:
      - ${SHARED_DATA}/downloads:/data/downloads
      - ${SERVICE_DATA}/filebroser/config:/config
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=filebrowser
      - homepage.icon=filebrowser.png
      - homepage.href=http://filebrowser.server.home
      - homepage.description=File server
      - traefik.enable=true
      - traefik.http.routers.filebrowser.rule=Host(`filebrowser.server.home`)
      - traefik.http.routers.filebrowser.entrypoints=web
      - traefik.http.services.filebrowser.loadbalancer.server.port=8080
    networks:
      internal_network:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - ${SERVICE_DATA}/transmission/config:/config
      - ${SHARED_DATA}/downloads:/downloads
      - ${SHARED_DATA}/watch:/watch
    ports:
      - ${TRANSMISSION_UI_PORT:-9091}:9091
      - 51413:51413
      - 51413:51413/udp
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://transmission.server.home/
      - homepage.description=Torrent client
      - traefik.enable=true
      - traefik.http.routers.transmission.rule=Host(`transmission.server.home`)
      - traefik.http.routers.transmission.entrypoints=web
      - traefik.http.services.transmission.loadbalancer.server.port=9091
    networks:
      internal_network:
