version: "3.7"
services:
  miniserve:
    image: docker.io/svenstaro/miniserve
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - MINISERVE_MKDIR_ENABLED=true
      - MINISERVE_SHOW_WGET_FOOTER=true
      - MINISERVE_DIRS_FIRST=true
      - MINISERVE_README=true
      - MINISERVE_ENABLE_TAR=true
      - MINISERVE_ENABLE_TAR_GZ=true
    volumes:
      - ${SHARED_DATA}/downloads:/data/downloads
      - ${SERVICE_DATA}/miniserve/config:/config
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=miniserve
      - homepage.icon=files.png
      - homepage.href=http://miniserve.mistborn/
      - homepage.description=File server
      - "traefik.enable=true"
      - "traefik.http.routers.miniserve-http.rule=Host(`miniserve.mistborn`)"
      - "traefik.http.routers.miniserve-http.entrypoints=web"
      - "traefik.http.routers.miniserve-http.middlewares=mistborn_auth@file"
      - "traefik.http.routers.miniserve-https.rule=Host(`miniserve.mistborn`)"
      - "traefik.http.routers.miniserve-https.entrypoints=websecure"
      - "traefik.http.routers.miniserve-https.middlewares=mistborn_auth@file"
      - "traefik.http.routers.miniserve-https.tls.certresolver=basic"
      - "traefik.http.services.miniserve-service.loadbalancer.server.port=8080"
    command: /data --upload-files
  filebrowser:
    image: hurlenko/filebrowser
    restart: unless-stopped
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
      - FB_BASEURL=/filebrowser
    volumes:
      - ${SHARED_DATA}/downloads:/data/downloads
      - ${SERVICE_DATA}/filebroser/config:/config
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=filebrowser
      - homepage.icon=filebrowser.png
      - homepage.href=http://filebrowser.mistborn/
      - homepage.description=File server
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser-http.rule=Host(`filebrowser.mistborn`)"
      - "traefik.http.routers.filebrowser-http.entrypoints=web"
      - "traefik.http.routers.filebrowser-http.middlewares=mistborn_auth@file"
      - "traefik.http.routers.filebrowser-https.rule=Host(`filebrowser.mistborn`)"
      - "traefik.http.routers.filebrowser-https.entrypoints=websecure"
      - "traefik.http.routers.filebrowser-https.middlewares=mistborn_auth@file"
      - "traefik.http.routers.filebrowser-https.tls.certresolver=basic"
      - "traefik.http.services.filebrowser-service.loadbalancer.server.port=8080"
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
    volumes:
      - ${SERVICE_DATA}/transmission/config:/config
      - ${SHARED_DATA}/downloads:/downloads
      - ${SHARED_DATA}/watch:/watch
    env_file: ../.env
    labels:
      - homepage.group=Files
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=http://transmission.mistborn/
      - homepage.description=Torrent client
      - "traefik.enable=true"
      - "traefik.http.routers.transmission-http.rule=Host(`transmission.mistborn`)"
      - "traefik.http.routers.transmission-http.entrypoints=web"
      - "traefik.http.routers.transmission-http.middlewares=mistborn_auth@file"
      - "traefik.http.routers.transmission-https.rule=Host(`transmission.mistborn`)"
      - "traefik.http.routers.transmission-https.entrypoints=websecure"
      - "traefik.http.routers.transmission-https.middlewares=mistborn_auth@file"
      - "traefik.http.routers.transmission-https.tls.certresolver=basic"
      - "traefik.http.services.transmission-service.loadbalancer.server.port=9091"
networks:
  default:
    name: mistborn_default
    external: true
