networks:
  internal_network:
    external: true

services:
  homeassistant:
    image: linuxserver/homeassistant
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
    volumes:
      - ${SERVICE_DATA}/homeassistant/config:/config # Contains all relevant configuration files.
    env_file: ../.env
    labels:
      - homepage.group=Smart Home
      - homepage.name=HomeAssistant
      - homepage.icon=home-assistant.png
      - homepage.href=http://homeassistant.server.home
      - homepage.description=Smart home automation manager
      - traefik.enable=true
      - traefik.http.routers.homeassistant.rule=Host(`homeassistant.server.home`)
      - traefik.http.routers.homeassistant.entrypoints=web
      - traefik.http.services.homeassistant.loadbalancer.server.port=8123
    networks:
      internal_network:
  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
    volumes:
      - ${SERVICE_DATA}/mosquitto:/mosquitto
    env_file: ../.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.mosquitto.rule=Host(`mosquitto.server.home`)
      - traefik.http.routers.mosquitto.entrypoints=web
      - traefik.http.services.mosquitto.loadbalancer.server.port=1883
    networks:
      internal_network:
  node-red:
    image: nodered/node-red
    restart: unless-stopped
    user: ${PUID}:${PGID}
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      - TZ=${TZ} # Specify a timezone to use e.g. Europe/London.
      - PUID=${PUID} # UID of user to take ownership of application/files
      - PGID=${PGID} # GID of user to take ownership of application/files
    volumes:
      - ${SERVICE_DATA}/node-red:/data
    env_file: ../.env
    labels:
      - homepage.group=Smart Home
      - homepage.name=NodeRed
      - homepage.icon=node-red.png
      - homepage.href=http://nodered.server.home
      - homepage.description=Smart home automation
      - traefik.enable=true
      - traefik.http.routers.nodered.rule=Host(`nodered.server.home`)
      - traefik.http.routers.nodered.entrypoints=web
      - traefik.http.services.nodered.loadbalancer.server.port=1880
    networks:
      internal_network:
