networks:
  internal_network:
    external: true

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - ${SERVICE_DATA}/mealie/data:/app/data/
    environment:
      - ALLOW_SIGNUP=true
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.server.home
    env_file: ../.env
    labels:
      - homepage.group=Tools
      - homepage.name=Mealie
      - homepage.icon=mealie.png
      - homepage.href=http://mealie.server.home/
      - homepage.description=Recipe manager
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`mealie.server.home`)
      - traefik.http.routers.mealie.entrypoints=web
      - traefik.http.services.mealie.loadbalancer.server.port=9000
    networks:
      internal_network:
